# Generated by Django 5.2.7 on 2025-10-30 16:40

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('currency', models.CharField(default='GHC', max_length=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=20)),
                ('availability', models.CharField(default='Always Available', max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ord_id', models.CharField(default=api.models.generate_order_id, max_length=15, unique=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('delivery_address', models.CharField(max_length=500)),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=50)),
                ('payment_status', models.CharField(default='Unpaid', max_length=50)),
                ('currency', models.CharField(default='GHC', max_length=5)),
                ('special_instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='api.orderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
