# Generated by Copilot on 2025-10-30
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0003_payment_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant'),
        ),
    ]
