# Generated by Django 5.2.7 on 2025-12-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_is_suspended_restaurant_suspension_reason'),
        ('api', '0006_paymentrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHC', max_length=5)),
                ('max_dishes', models.PositiveIntegerField()),
                ('max_tables', models.PositiveIntegerField()),
                ('max_orders', models.PositiveIntegerField()),
                ('max_reservations', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.restaurant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.subscriptionpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
