# Generated by Django 5.2.7 on 2025-11-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_operationalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalhours',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='operationalhours',
            unique_together={('restaurant', 'day_of_week')},
        ),
    ]
