# Generated by Django 5.2.7 on 2025-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_operationalhours_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='withdrawal_pin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
