# Generated by Django 5.2.7 on 2025-12-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurant_withdrawal_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
