# Generated by Django 5.2.7 on 2025-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_is_suspended_restaurant_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_registration_status',
            field=models.CharField(default='INCOMPLETE', max_length=20),
        ),
    ]
