# Generated by Django 5.2.7 on 2025-12-24 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_profile_registration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_id', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('waba_id', models.CharField(blank=True, max_length=64, null=True)),
                ('business_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='accounts.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('from_wa_id', models.CharField(max_length=20)),
                ('message_type', models.CharField(blank=True, default='', max_length=40)),
                ('text', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='integrations.whatsappcontact')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='integrations.whatsappintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.whatsappintegration'),
        ),
        migrations.CreateModel(
            name='WhatsAppOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_wa_id', models.CharField(max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('message_type', models.CharField(blank=True, default='text', max_length=40)),
                ('text', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('sent_ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='integrations.whatsappcontact')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='integrations.whatsappintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcontact',
            unique_together={('integration', 'wa_id')},
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('START', 'START'), ('ORDER_PICK_ITEMS', 'ORDER_PICK_ITEMS'), ('ORDER_ADDRESS', 'ORDER_ADDRESS'), ('RESERVE_PICK_TABLE', 'RESERVE_PICK_TABLE'), ('RESERVE_PICK_DATETIME', 'RESERVE_PICK_DATETIME')], default='START', max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_open', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='integrations.whatsappcontact')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='integrations.whatsappintegration')),
            ],
            options={
                'indexes': [models.Index(fields=['integration', 'contact', 'is_open', 'updated_at'], name='integration_integra_0529bd_idx')],
            },
        ),
    ]
